### ISSUE TITLE
Bug: Width of footer container doesn't match the content container width

### ISSUE THREAD

**Issue by darickdang** [xmtp/xmtp-dot-org#107]
## Describe the bug

The width of the footer container is wider than the width of the container from the content section above it.

## Steps to Reproduce

Scroll down to the footer and compare it to the content section above.

## Expected behavior

The width of the footer container should be the same as the rest of the page.

## Screenshots

<img width="541" alt="CleanShot 2022-09-14 at 00 09 37@2x" src="https://user-images.githubusercontent.com/1136890/190064775-cae36aed-8368-4c9f-9a22-80bd09873db6.png">

## Additional context

Design screenshot:

<img width="610" alt="CleanShot 2022-09-14 at 00 10 57@2x" src="https://user-images.githubusercontent.com/1136890/190064804-c072de30-02a6-4179-93e0-c0520730e70a.png">

### Desktop

Please complete the following information if you think it is relevant to the bug:

- OS & Version: macOS Monterey
- Browser & Version: Safari 15.6.1

**Comment by jhaaaa** [comment]
Addressed in https://github.com/xmtp/xmtp-dot-org/pull/176
