### ISSUE TITLE
Bug: link up blog author names and whole Community tiles

### ISSUE THREAD

**Issue by saulmc** [xmtp/xmtp-dot-org#142]
- [x] Announcement link to litepaper
- [x] Blog row author links
- [x] Blog row tag links
- [x] Community tiles

**Comment by jhaaaa** [comment]
@saulmc We had the Community tiles linked up, but we *think* Darick changed them back to just linking the CTA text. Just want to be sure to check with Darick when he gets back to see if he has any concerns with linking them up again. Keeping this open to track.

**Comment by jhaaaa** [comment]
Addressed in https://github.com/xmtp/xmtp-dot-org/pull/179 - thank you!
