### ISSUE TITLE
Update mobile menu UX - hamburger to kabob

### ISSUE THREAD

**Issue by darickdang** [xmtp/xmtp-dot-org#160]
## Describe the bug

On mobile devices, the search bar covers the other elements in the top navigation bar.

## Steps to Reproduce

1. Go to any page on the developer portal on a mobile device
2. See the search bar in the top navigation covering most of the container

## Expected behavior

This is the intended design. We can keep the current hamburger button for now but would like this to be updated to the design as a fast follow.

<img width="1341" alt="CleanShot 2022-09-30 at 21 19 34@2x" src="https://user-images.githubusercontent.com/1136890/193392262-9cad74e7-266c-4b08-92bd-e25347623f32.png">

## Screenshots

This is the current implementation:

<img width="464" alt="CleanShot 2022-09-30 at 21 05 10@2x" src="https://user-images.githubusercontent.com/1136890/193392274-32303e3b-4ef5-461d-8738-28bf90d29837.png">

## Additional context

—

### Smartphone

Please complete the following information if you think it is relevant to the bug:

- Device: Responsive inspector on Chrome in the Pixel 6 viewport
- Browser: Chrome

**Comment by jhaaaa** [comment]
J-Ha to map out current and planned IA of the site to see if both kebab and hamburger menus will be useful for mobile use.

**Comment by jhaaaa** [comment]
Also, even if we keep the hamburger menu only - per Darick - please make it smaller.

**Comment by jhaaaa** [comment]
Hi there @darickdang - just wanted to follow up on this and as promised, provide the analytics for mobile devices. These are numbers for the last week:

![Image](https://user-images.githubusercontent.com/5481259/195947073-a9c46177-19c6-46e4-b22f-5735206a333c.png)

What do you think?

I defer to you, of course, but I'll humbly share that my preference, for now, based on current mobile usage numbers, is to stick with the default UX pattern provided by Docusaurus - just reducing the size of the hamburger icon, as you've requested. 

What do you think? <3

**Comment by jhaaaa** [comment]
Per chat with Vehid today, he is going to change the hamburger icon to a kebab icon and move it to the top right to match the designs.

Let's see if we can keep the behavior of the underlying menu itself the same, though everything will need to orient to opening from the right instead of the left. Let's see how this goes. <3

**Comment by jhaaaa** [comment]
Addressed in https://github.com/xmtp/xmtp-dot-org/pull/195
