### ISSUE TITLE
Bug: Last item in this issue: SDK and tools body content container doesn't match docs or home page (orig Bug: XMTP logo in header changes position)

### ISSUE THREAD

**Issue by saulmc** [xmtp/xmtp-dot-org#173]
## Describe the bug

When clicking through the site, the XMTP logo does not stay in a fixed location.

It seems there are 3 different width settings to align:
- Homepage
- Docusaurus docs page
- Docusaurus Page

![CleanShot 2022-10-03 at 16 32 21](https://user-images.githubusercontent.com/510695/193704431-16e65d08-d0ae-4dcd-bd9d-16ccec704631.gif)

EDIT: I actually think the whole site grid uses different widths in these 3 contexts.

**Comment by jhaaaa** [comment]
Addressed in https://github.com/xmtp/xmtp-dot-org/pull/177 - thank you!

**Comment by jhaaaa** [comment]
@vehid - Ah, it looks like the [SDK and tools page](https://xmtp.org/sdks-and-tools) body content container is still not matching the body content container on the home and doc pages. Might it be possible to refine this, please? =)

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/5481259/194583913-c9768475-fdfd-4a1a-a456-c54c0de740e2.png">

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/5481259/194583964-df854fde-5973-41a2-ae86-8f3181dac90c.png">

**Comment by jhaaaa** [comment]
Fixed via https://github.com/xmtp/xmtp-dot-org/pull/191
