### ISSUE TITLE
Bug: Navbar resizes after page load

### ISSUE THREAD

**Issue by saulmc** [xmtp/xmtp-dot-org#174]
## Describe the bug

The navbar is being repainted at different widths:

![CleanShot 2022-10-03 at 16 39 54](https://user-images.githubusercontent.com/510695/193705193-4eb766bd-6668-4d05-a045-96505c606f0c.gif)

**Comment by jhaaaa** [comment]
Addressed in https://github.com/xmtp/xmtp-dot-org/pull/177 - thank you!
