### ISSUE TITLE
Top of main container of homepage has a blurred background on large viewports

### ISSUE THREAD

**Issue by darickdang** [xmtp/xmtp-dot-org#182]
## Describe the bug

The blurred background that (correctly) appears on the /docs/* pages shows up on the homepage when the viewport gets wider than ~1800px.

## Steps to Reproduce

1. Go to the Developer Portal homepage
2. Widen the browser width to be wider than 1800px
3. See the blurred background appear

## Expected behavior

The blurred background that appears on /docs/* should not appear at all on the homepage at all

## Screenshots

Current implementation:

<img width="1712" alt="CleanShot 2022-10-07 at 13 28 14@2x" src="https://user-images.githubusercontent.com/1136890/194647563-76f46314-9fa1-4ed9-91a6-973d249a34ad.png">

## Additional context

—

### Desktop

Please complete the following information if you think it is relevant to the bug:

- OS & Version: macOS Monterey 12.6
- Browser & Version: Chrome 105.0.5195.102

**Comment by jhaaaa** [comment]
Thank you for this, @darickdang! Fixed via https://github.com/xmtp/xmtp-dot-org/pull/191
