### ISSUE TITLE
Bug: Link to "V2 topics and message presentation flow" on invitation page not working

### ISSUE THREAD

**Issue by galligan** [xmtp/xmtp-dot-org#205]
## Describe the bug

On the page [Invitation and message encryption with XMTP](https://xmtp.org/docs/dev-concepts/invitation-and-message-encryption) the link to "[XMTP V2 topics and message presentation flow](https://xmtp.org/docs/dev-concepts/architectural-overview#xmtp-v2-topics-and-message-presentation-flow)" is not working.

![CleanShot 2022-11-05 at 08 29 21@2x](https://user-images.githubusercontent.com/25037981/200127492-7a7adc08-dd6f-48e6-8fa3-5bcfa75c2364.png)

## Steps to Reproduce

1. Go to [Invitation and message encryption with XMTP](https://xmtp.org/docs/dev-concepts/invitation-and-message-encryption)
2. Scroll down to the header "XMTP V2 invitation and message encryption"
3. Observe in the second paragraph the link to "XMTP V2 topics and message presentation flow"
4. Notice that a click doesn't work

## Expected behavior

Interacting with the link should take me to [XMTP V2 topics and message presentation flow](https://xmtp.org/docs/dev-concepts/architectural-overview#xmtp-v2-topics-and-message-presentation-flow)

## Additional context

Line 15 on the invitation document reads:

```
To learn more about invitations and messages, see [XMTP V2 topics and message presentation flow](#xmtp-v2-topics-and-message-presentation-flow).
<!--once specs are published, add link to Client Layer in The XMTP Protocol specifications.-->
```

I believe the link needs to read something like…

```
(../architectural-overview#xmtp-v2-topics-and-message-presentation-flow)
```

**Comment by jhaaaa** [comment]
Thank you for this @galligan - fixed this in https://github.com/xmtp/xmtp-dot-org/pull/232.

I apologize that I am so late in getting to this! I've been relying on Slack GitHub notifications and this did not come through that channel. I will get my workflow fixed ASAP. Again, so sorry for the delay! =(
