### ISSUE TITLE
Bug: Page not found "Built with XMTP"

### ISSUE THREAD

**Issue by omahs** [xmtp/xmtp-dot-org#247]
1. Go to https://xmtp.org/docs/dev-concepts/contributing
2. Scroll and click on "Built with XMTP"

**Comment by jhaaaa** [comment]
Addressed in https://github.com/xmtp/xmtp-dot-org/pull/256. 

Thank you so much for taking the time to report the bug, @omahs! 🙇🏻‍♀️💓
