### ISSUE TITLE
Add TypeDoc support

### ISSUE THREAD

**Issue by galligan** [xmtp/xmtp-dot-org#4]
https://www.npmjs.com/package/docusaurus-plugin-typedoc

This will enable us to automatically pull in the `xmtp/xmtp-js` documentation that's built using TypeDoc ([which is here](https://xmtp-js.pages.dev)).

**Comment by jhaaaa** [comment]
obsolete. we have returned to providing ref docs here only: https://xmtp-js.pages.dev/modules
