### ISSUE TITLE
Background fade obscures card text on far left and far right (re: Add background fade to left slider arrow)

### ISSUE THREAD

**Issue by darickdang** [xmtp/xmtp-dot-org#81]
**Describe the bug**
When the slider for the "SDK and tools" is scrolled, the left edge is abruptly cutoff. We should add a fade behind the arrow when it is scrolled that would also match the right arrow background behavior.

**To Reproduce**
—

**Expected behavior**
—

**Screenshots**
<img width="632" alt="CleanShot 2022-09-08 at 14 52 10@2x" src="https://user-images.githubusercontent.com/1136890/189232650-5a15bcf0-641e-4d03-9c46-6213ef30ccd0.png">

**Additional context**
—

**Comment by jhaaaa** [comment]
Addressed in https://github.com/xmtp/xmtp-dot-org/pull/195
