### ISSUE TITLE
Bug: Vision block text layout could be more logically grouped

### ISSUE THREAD

**Issue by galligan** [xmtp/xmtp-dot-org#94]
## Describe the bug

Currently the Vision block shows the text as follows:

```
Learn about the XMTP
roadmap, case studies, and
more
```

It could be improved with a more logical grouping that reads better:

```
Learn about the
XMTP roadmap, case studies,
and more
```

or

```
Read the XMTP Litepaper,
case studies, roadmap,
and more…
```

## Screenshots

<img width="453" alt="CleanShot 2022-09-09 at 14 55 59@2x" src="https://user-images.githubusercontent.com/25037981/189424374-fca0d953-6148-405a-bf22-acaa92c9bf79.png">

**Comment by jhaaaa** [comment]
obsolete
