### ISSUE TITLE
Bug: Hero text could be grouped more logically

### ISSUE THREAD

**Issue by galligan** [xmtp/xmtp-dot-org#95]
## Describe the bug

Currently it reads:

```
The open protocol, network,
and standards for secure
web3 messaging
```

Perhaps it would be helpful to read like:

```
The open protocol, network,
and standards for
secure web3 messaging
```

Or possibly (until we're pushing standards more) to get it really tight:

```
The open protocol and network
for secure web3 messaging
```

## Screenshots

<img width="781" alt="CleanShot 2022-09-09 at 15 03 49@2x" src="https://user-images.githubusercontent.com/25037981/189425147-9eddbf20-b6de-44ee-b0c6-a2eabd096ed3.png">

**Comment by jhaaaa** [comment]
obsolete
