### ISSUE TITLE
Bug: Under-hero text could emphasize blockchain account messaging more strongly

### ISSUE THREAD

**Issue by galligan** [xmtp/xmtp-dot-org#96]
## Describe the bug

Currently the section reads:

```
Build with XMTP to send alerts, announcements, and messages
between blockchain accounts
```

Also, note the text grouping could be a bit better…

I might offer a slight reworking to put greater emphasis on a complete thought before the break, with additional follow-up such as:

```
Build with XMTP to send messages between blockchain accounts,
including DMs, alerts, announcements, notifications, and more…
```

## Screenshots

<img width="736" alt="CleanShot 2022-09-09 at 15 05 11@2x" src="https://user-images.githubusercontent.com/25037981/189425590-aafee5a1-0a47-4eae-9b3f-dd386f47b69f.png">

**Comment by jhaaaa** [comment]
Complete as of v1 release. 

![image](https://user-images.githubusercontent.com/5481259/193934761-f4146ae1-8052-4ea7-aeb2-0c7a1c86490d.png)
